Mobile menu
Luchy-B/My-Portfolio pull request #7
Opened 2022-11-23 18:21 UTC by Luchy-B

- Add linters
- Add JS file

2022-11-23 18:47 UTC, ShadyShawkat requested changes
## Hi Team, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-23 18:47 UTC, ShadyShawkat commented on index.html
> +                    </ul>
- Please make sure to follow the design guidelines as much as possible, which include:
   - [ ] Aligning the navigation links to the left of the mobile menu.
   - [ ] Separating each link with a horizontal line to match the given design.
   - [ ] Aligning the "close" button to the right of the mobile menu.
   - [ ] Using the given font family and styling to match the given design.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/203623550-c198c691-0271-426c-9978-c7f67c130446.png) | ![image](https://user-images.githubusercontent.com/62290545/203623499-932b2efe-ccf0-4838-b754-bdbafecef420.png) |

2022-11-23 18:47 UTC, ShadyShawkat commented on .eslintrc.json
> +
- [ ] Please make sure to set up the EsLint linters correctly. Kindly update the `./github/workflows/linters.yml` file using [this](https://github.com/microverseinc/linters-config/blob/master/html-css-js/.github/workflows/linters.yml) configuration from the [linters setup for HTML, CSS, and JavaScript](https://github.com/microverseinc/linters-config/tree/master/html-css-js) projects.

- This is a required change to use the correct linters setup. However, in the future, setting up the inters incorrectly can result in the invalidation of your submission.

2022-11-23 18:47 UTC, ShadyShawkat commented on index.html
> +                              </div>
- [ ] Kindly eliminate the horizontal scroll in your website which results in this excess white space appearing on the right for your project to be more professional.
![image](https://user-images.githubusercontent.com/62290545/203624685-bb5d8c18-0394-42ff-81cd-505c90aec350.png)

2022-11-24 08:53 UTC, Davidosky007 approved these changes
Hi @Luchy-B 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* Good looking readme file 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-24 09:13 UTC, merged